language: python
services:
- postgresql
python:
- "3.5.1"
# command to install dependencies
install: "pip3 install -r requirements/testing.txt"
before_script:
- psql -c 'create database taskbuster_db;' -U postgres
- python3 manage.py syncdb -migrate -noinput
# command to run tests
script: "python3 manage.py test"
