language: python
sudo: required
services:
- postgresql
python:
- "3.5.1"
# command to install dependencies
install: "pip3 install -r requirements/testing.txt"
before_script:
- psql -c 'create database taskbuster_db;' -U postgres
- export DJANGO_SETTINGS_MODULE="taskbuster.settings.testing"
- export SECRET_KEY="%@suos(hri6mctkap-nyy6=*hxw03(deytyh)q8fna-9wk!l%@"
- export DATABASE_NAME='taskbuster_db'
- export DATABASE_USER=''
- export DATABASE_PASSWORD=''
- touch google_user.json
- echo "{"Email": "taskbustertester@gmail.com", "Password": "foobarsammy"}" > google_user.json
- touch allauth_fixture.json
- echo "[
{
  "model": "auth.user",
  "pk": 1,
  "fields": {
    "is_staff": true,
    "user_permissions": [],
    "first_name": "",
    "password": "pbkdf2_sha256$20000$Y2Vz2LQeUa4g$8sPAHnjHp+381R+uSQgfvm2U6DaI5qqEggu6e6lnoI8=",
    "last_login": "2016-04-18T01:06:58.197Z",
    "email": "samuel.gonzalesluna@gmail.com",
    "is_active": true,
    "username": "tbsamuelcg",
    "groups": [],
    "is_superuser": true,
    "last_name": "",
    "date_joined": "2016-04-18T01:06:17.771Z"
  }
},
{
  "model": "auth.user",
  "pk": 2,
  "fields": {
    "is_staff": false,
    "user_permissions": [],
    "first_name": "",
    "password": "pbkdf2_sha256$20000$jjCK0380WIji$wtK+XZhQxj6lBtR0yYHiud/U4ceCnBibtaOSwXr6JGM=",
    "last_login": "2016-04-18T01:07:43.053Z",
    "email": "s@g.com",
    "is_active": true,
    "username": "s",
    "groups": [],
    "is_superuser": false,
    "last_name": "",
    "date_joined": "2016-04-18T01:07:43.021Z"
  }
},
{
  "model": "sites.site",
  "pk": 2,
  "fields": {
    "domain": "example.com",
    "name": "example.com"
  }
},
{
  "model": "account.emailaddress",
  "pk": 1,
  "fields": {
    "verified": false,
    "user": [
      "s"
    ],
    "primary": true,
    "email": "s@g.com"
  }
}
]" > allauth_fixture.json
- python3 manage.py migrate
# command to run tests
script: "python3 manage.py test"
