language: python
sudo: required
services:
  - postgresql
python:
  - "3.5.1"
# command to install dependencies
install: "pip3 install -r requirements/testing.txt"
before_script:
- psql -c 'create database taskbuster_db;' -U postgres
- export DJANGO_SETTINGS_MODULE="taskbuster.settings.testing"
- export SECRET_KEY="%@suos(hri6mctkap-nyy6=*hxw03(deytyh)q8fna-9wk!l%@"
- export DATABASE_NAME='taskbuster_db'
- export DATABASE_USER=''
- export DATABASE_PASSWORD=''
- python3 manage.py migrate
# command to run tests
script: "python3 manage.py test"
